-- V12: Notification subscription and delivery log tables

CREATE TABLE NOTIFICATION_SUBSCRIPTION (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID          NUMBER         NOT NULL,
    CHANNEL_TYPE    VARCHAR2(50)   NOT NULL,
    EVENTS          VARCHAR2(100)  NOT NULL,
    CONFIG_JSON     CLOB           NOT NULL,
    ACTIVE          NUMBER(1)      DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NOTIF_SUB_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB_DEFINITION(JOB_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NOTIF_SUB_JOB    ON NOTIFICATION_SUBSCRIPTION(JOB_ID);
CREATE INDEX IDX_NOTIF_SUB_ACTIVE ON NOTIFICATION_SUBSCRIPTION(ACTIVE);

CREATE TABLE NOTIFICATION_DELIVERY_LOG (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SUBSCRIPTION_ID NUMBER         NOT NULL,
    RUN_ID          NUMBER         NOT NULL,
    CHANNEL_TYPE    VARCHAR2(50)   NOT NULL,
    EVENTS_JSON     CLOB,
    CONFIG_JSON     CLOB,
    STATUS          VARCHAR2(20)   NOT NULL
                        CHECK (STATUS IN ('PENDING','SENT','FAILED')),
    ERROR_MESSAGE   CLOB,
    ATTEMPT_COUNT   NUMBER         DEFAULT 0 NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    SENT_AT         TIMESTAMP,
    CONSTRAINT FK_NOTIF_LOG_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES NOTIFICATION_SUBSCRIPTION(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NOTIF_LOG_SUB     ON NOTIFICATION_DELIVERY_LOG(SUBSCRIPTION_ID);
CREATE INDEX IDX_NOTIF_LOG_RUN     ON NOTIFICATION_DELIVERY_LOG(RUN_ID);
CREATE INDEX IDX_NOTIF_LOG_STATUS  ON NOTIFICATION_DELIVERY_LOG(STATUS);
