CREATE TABLE JOB_DEFINITION (
    JOB_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_NAME        VARCHAR2(200)  NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    WORKING_DIR     VARCHAR2(500)  NOT NULL,
    ENABLED         CHAR(1)        DEFAULT 'Y' NOT NULL CHECK (ENABLED IN ('Y','N')),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_JOB_NAME UNIQUE (JOB_NAME)
);

CREATE TABLE JOB_STEP (
    STEP_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID              NUMBER         NOT NULL,
    STEP_NAME           VARCHAR2(200)  NOT NULL,
    STEP_ORDER          NUMBER         NOT NULL,
    STEP_TYPE           VARCHAR2(50)   NOT NULL
                        CHECK (STEP_TYPE IN ('ENV_SETUP','LOG_CLEANUP','JAVA_EXEC','SFTP','ARCHIVE')),
    STEP_CONFIG         CLOB,
    CONTINUE_ON_FAILURE CHAR(1)        DEFAULT 'N' NOT NULL CHECK (CONTINUE_ON_FAILURE IN ('Y','N')),
    ENABLED             CHAR(1)        DEFAULT 'Y' NOT NULL CHECK (ENABLED IN ('Y','N')),
    CONSTRAINT FK_STEP_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB_DEFINITION(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_STEP_ORDER UNIQUE (JOB_ID, STEP_ORDER)
);

CREATE TABLE JOB_ENV_VAR (
    ENV_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID      NUMBER,
    VAR_NAME    VARCHAR2(200)  NOT NULL,
    VAR_VALUE   VARCHAR2(2000) NOT NULL,
    IS_GLOBAL   CHAR(1)        DEFAULT 'N' NOT NULL CHECK (IS_GLOBAL IN ('Y','N')),
    CONSTRAINT FK_ENV_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB_DEFINITION(JOB_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ENV_JOB ON JOB_ENV_VAR(JOB_ID);
CREATE INDEX IDX_ENV_GLOBAL ON JOB_ENV_VAR(IS_GLOBAL);
