CREATE TABLE JOB_RUN (
    RUN_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID          NUMBER         NOT NULL,
    TRIGGERED_BY    VARCHAR2(200),
    TRIGGER_TYPE    VARCHAR2(20)   NOT NULL
                    CHECK (TRIGGER_TYPE IN ('MANUAL','SCHEDULED','API')),
    STATUS          VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL
                    CHECK (STATUS IN ('PENDING','RUNNING','SUCCESS','FAILED','PARTIAL','CANCELLED')),
    STARTED_AT      TIMESTAMP,
    ENDED_AT        TIMESTAMP,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_RUN_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB_DEFINITION(JOB_ID)
);

CREATE TABLE JOB_RUN_STEP (
    RUN_STEP_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RUN_ID          NUMBER         NOT NULL,
    STEP_ID         NUMBER         NOT NULL,
    STEP_ORDER      NUMBER         NOT NULL,
    STATUS          VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL
                    CHECK (STATUS IN ('PENDING','RUNNING','SUCCESS','FAILED','SKIPPED')),
    LOG_OUTPUT      CLOB,
    EXIT_CODE       NUMBER,
    STARTED_AT      TIMESTAMP,
    ENDED_AT        TIMESTAMP,
    CONSTRAINT FK_RUN_STEP_RUN  FOREIGN KEY (RUN_ID)  REFERENCES JOB_RUN(RUN_ID)  ON DELETE CASCADE,
    CONSTRAINT FK_RUN_STEP_STEP FOREIGN KEY (STEP_ID) REFERENCES JOB_STEP(STEP_ID)
);

CREATE INDEX IDX_RUN_JOB    ON JOB_RUN(JOB_ID);
CREATE INDEX IDX_RUN_STATUS ON JOB_RUN(STATUS);
CREATE INDEX IDX_RUN_STEP_RUN ON JOB_RUN_STEP(RUN_ID);
