CREATE TABLE JOB_SCHEDULE (
    SCHEDULE_ID     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID          NUMBER         NOT NULL,
    CRON_EXPRESSION VARCHAR2(100)  NOT NULL,
    ENABLED         CHAR(1)        DEFAULT 'Y' NOT NULL CHECK (ENABLED IN ('Y','N')),
    NEXT_FIRE_TIME  TIMESTAMP,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_SCHEDULE_JOB FOREIGN KEY (JOB_ID) REFERENCES JOB_DEFINITION(JOB_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_JOB_SCHEDULE UNIQUE (JOB_ID)
);

CREATE TABLE JOB_CREDENTIAL (
    CREDENTIAL_ID   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CREDENTIAL_REF  VARCHAR2(100)  NOT NULL,
    CRED_TYPE       VARCHAR2(20)   NOT NULL CHECK (CRED_TYPE IN ('PASSWORD','SSH_KEY')),
    CRED_VALUE      VARCHAR2(4000) NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_CRED_REF UNIQUE (CREDENTIAL_REF)
);

CREATE TABLE AUDIT_LOG (
    AUDIT_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME    VARCHAR2(200)  NOT NULL,
    ACTION      VARCHAR2(200)  NOT NULL,
    ENTITY_TYPE VARCHAR2(100),
    ENTITY_ID   NUMBER,
    DETAIL      VARCHAR2(2000),
    CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_USER   ON AUDIT_LOG(USERNAME);
CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
