CREATE TABLE APP_USER (
    USER_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME          VARCHAR2(100) NOT NULL,
    PASSWORD_HASH     VARCHAR2(200) NOT NULL,
    ROLE              VARCHAR2(20)  NOT NULL
                      CHECK (ROLE IN ('ADMIN','OPERATOR','VIEWER')),
    ENABLED           CHAR(1)       DEFAULT 'Y' NOT NULL CHECK (ENABLED IN ('Y','N')),
    PASSWORD_EXPIRED  CHAR(1)       DEFAULT 'N' NOT NULL CHECK (PASSWORD_EXPIRED IN ('Y','N')),
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_USERNAME UNIQUE (USERNAME)
);

COMMENT ON COLUMN APP_USER.PASSWORD_HASH IS 'BCrypt hashed password';
COMMENT ON COLUMN APP_USER.PASSWORD_EXPIRED IS 'Y forces password change on next login';

-- Default admin (password = 'changeme' — BCrypt hash of 'changeme')
INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, PASSWORD_EXPIRED)
VALUES ('admin', '$2a$12$8qJ.129ZKqEzYgEYQgEwXO7PjYkLxqKJWbFZxXqLqKJWbFZxXqLqK', 'ADMIN', 'Y');

-- Default operator
INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, PASSWORD_EXPIRED)
VALUES ('operator', '$2a$12$8qJ.129ZKqEzYgEYQgEwXO7PjYkLxqKJWbFZxXqLqKJWbFZxXqLqK', 'OPERATOR', 'Y');

-- Default viewer
INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, PASSWORD_EXPIRED)
VALUES ('viewer', '$2a$12$8qJ.129ZKqEzYgEYQgEwXO7PjYkLxqKJWbFZxXqLqKJWbFZxXqLqK', 'VIEWER', 'Y');
